[project]
name = "django-project-starter"
version = "0.1.0"
description = ""
authors = [
    {name = "Fidel Quedet",email = "fidelquedet10@gmail.com"}
]
license = "MIT"
requires-python = ">=3.14,<4.0"
dependencies = [
    "django (>=5.2,<6.0)",
    "python-webpack-boilerplate (>=1.0.4,<2.0.0)",
    "django-extensions (>=4.1,<5.0)",
    "django-turbo-response (>=1.0.3,<2.0.0)",
    "django-formify (>=0.0.8,<0.0.9)",
    "psycopg2-binary (>=2.9.13,<3.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
